title: Juliane Woolslayer
logo: "/images/pic.png?raw=true" 
description: > 
Teacher transitioning to Data/Business Analyst. Recently earned my M.S. in Data Analytics. Experience with Excel, Power BI, Access, SQL and Python.
  <br><br>
 
  <a href="https://www.linkedin.com/in/julianewoolslayera2a922a8/">View My LinkedIn Profile</a> 

  
theme: jekyll-theme-minimal
 
  
