title: Juliane Woolslayer
logo: "/images/IMG_4743.JPG?raw=true" 
description: > 
  Data Analyst 
  <br><br>
 
  <a href="https://www.linkedin.com/in/julianewoolslayera2a922a8/">View My LinkedIn Profile</a> 

  
theme: jekyll-theme-minimal
 
  
